"""empty message

Revision ID: a98c337cafa5
Revises: ad9c7339b8b0
Create Date: 2026-01-21 22:36:17.019777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98c337cafa5'
down_revision = 'ad9c7339b8b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_bookings',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('number_of_people', sa.Integer(), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tour_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tour_bookings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tour_bookings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_tour_bookings_id'))

    op.drop_table('tour_bookings')
    # ### end Alembic commands ###
